[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build --workspace=backend"]

[start]
cmd = "npm run start --workspace=backend"
